on:
  workflow_dispatch:

jobs:
  Checkout_Repos:
    permissions: write-all
    runs-on: self-hosted
    steps:
      - name: Checkout dqx_dat_dump
        uses: actions/checkout@v4
        with:
          path: ./20250626/dqx_dat_dump
          ref: testing
          repository: KodywithaK/dqx_dat_dump

      - name: Checkout dqx-offline-localization
        uses: actions/checkout@v4
        with:
          path: ./20250626/dqx-offline-localization
          ref: "20250626"
          repository: KodywithaK/dqx-offline-localization

      - name: Checkout LocRes-Builder
        uses: actions/checkout@v4
        with:
          path: ./20250626/LocRes-Builder
          ref: main
          repository: KodywithaK/LocRes-Builder

  LocRes-Builder:
    needs: [Checkout_Repos]
    runs-on: self-hosted
    steps:
      - name: LocRes-Builder Inputs
        run: |
          # echo -e "::group::\033[0;34m Building LocRes-Builder's Inputs \033[0m"
          mkdir -p ${{ github.workspace }}/20250626/LocRes-Builder/INPUT

          cp "${{ github.workspace }}/20250626/dqx-offline-localization/pakchunk0-WindowsNoEditor.pak/Game/Content/Localization/Game/Game.locmeta.json" \
          "${{ github.workspace }}/20250626/LocRes-Builder/INPUT/locmeta.json"

          for lang in de en es fr it ja ko pt-BR zh-Hans zh-Hant; do jq \
            "to_entries| map(reduce . as \$obj ({};{\"key\": \$obj[\"key\"],\"value\": (\$obj[\"value\"]| to_entries| map({\"key\": .key,\"value\": [(if (.value[\"${lang}\"] != \"\")then (.value = .value[\"${lang}\"])else (.value = .value.ja)end)]| from_entries[]})| from_entries)}))| from_entries" \
            "${{ github.workspace }}/20250626/dqx-offline-localization/pakchunk0-WindowsNoEditor.pak/Game/Content/Localization/Game/Game.locres.json" \
            > "${{ github.workspace }}/20250626/LocRes-Builder/INPUT/${lang}.json"
          done
          # echo "::endgroup::"

      - name: LocRes-Builder Outputs
        run: |
          echo -e "::group::\033[0;34m Building LocRes-Builder's Outputs \033[0m"
            mkdir -p ${{ github.workspace }}/20250626/LocRes-Builder/OUTPUT

            python3 "${{ github.workspace }}/20250626/LocRes-Builder/src/main.py" \
            "${{ github.workspace }}/20250626/LocRes-Builder/INPUT/locmeta.json" \
            -o="${{ github.workspace }}/20250626/LocRes-Builder/OUTPUT" -f=json

            for lang in de en es fr it ja ko pt-BR zh-Hans zh-Hant; do \
              mkdir -p "${{ github.workspace }}/20250626/staging/${lang}/Game/Content/Localization/Game/${lang}"

              cp "${{ github.workspace }}/20250626/LocRes-Builder/OUTPUT/Game/${lang}/Game.locres" \
              "${{ github.workspace }}/20250626/staging/${lang}/Game/Content/Localization/Game/${lang}/Game.locres"

              mkdir -p "${{ github.workspace }}/20250626/staging/${lang}/Game/Content/Settings/Version"

              jq -n "{\"AppVersionString\": \"2.0.0\n$(echo -e ${lang}_v$(date -u +%F ))\"}" \
              > "${{ github.workspace }}/20250626/staging/${lang}/Game/Content/Settings/Version/version_settings.json"
            done
          echo "::endgroup::"

  YAML_to_ETP:
    needs: [Checkout_Repos, LocRes-Builder]
    runs-on: self-hosted
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          architecture: "x64"
          # python-version: '3.x'
          python-version: "3.11"
          cache: "pip" # caching pip dependencies

      - name: Split ETP.yaml
        run: |
          mkdir -p "${{ github.workspace }}/20250626/dqx-offline-localization/pakchunk0-WindowsNoEditor.pak/Game/Content/NonAssets/ETP"
          cd "${{ github.workspace }}/20250626/dqx-offline-localization/pakchunk0-WindowsNoEditor.pak/Game/Content/NonAssets/ETP"
          echo -e "Splitting ETP.yaml"
          yq -s ".filename + \".deleteme\"" --no-doc \
          "../ETP.yaml" \
          -o json -I2
          echo -e "Deleting .filename from *.deleteme"
          for file in ./*.deleteme; do \
            yq "del(.filename)" \
            "${file}" \
            > "${file%.*}" \
            -o json -I2
            
            rm "${file}"
          done

      - name: dqx_dat_dump
        run: |
          cd "${{ github.workspace }}/20250626/dqx_dat_dump"
          python -m venv venv
          source ./venv/bin/activate
          pip install -r requirements.txt
          cd ./tools/packing/

          for lang in de en es fr it ja ko pt-BR zh-Hans zh-Hant; do
            echo -e "::group::Packing \033[0;32m ETP_${lang}\033[0m"
              python pack_etp--KwK_20250626.py -L ${lang}
            echo "::endgroup::"
          done

          deactivate
          cd ~

  UnrealPak_-Create:
    needs: [Checkout_Repos, LocRes-Builder, YAML_to_ETP]
    runs-on: self-hosted
    steps:
      - name: UnrealPak -Create
        run: |
          mkdir -p \
          "${{ github.workspace }}/20250626/staging" \
          "${{ github.workspace }}/20250626/staging/releases"

          for PLATFORM in Switch WindowsNoEditor; do\
            for lang in de en es fr it ja ko pt-BR zh-Hans zh-Hant; do\
              mkdir -p \
              "${{ github.workspace }}/20250626/staging/${lang}" \
              "${{ github.workspace }}/20250626/staging/${lang}/Game/Content/NonAssets/ETP_ko"

              cp \
              "${{ github.workspace }}/20250626/staging/${lang}/Game/Content/NonAssets/ETP/*" \
              "${{ github.workspace }}/20250626/staging/${lang}/Game/Content/NonAssets/ETP_ko"

              if [[ ${PLATFORM} == "ios" || ${PLATFORM} == "Switch" ]]; then
                DESTINATION="Holiday";
              else
                DESTINATION="Game";
              fi
                echo -e "::group::Creating \033[0;34m responseFile--pakchunk0-${PLATFORM}_Latest.pak.txt \033[0m"
                  echo -e \
                  "\
                  \"..\\..\\..\\..\\\actions-runner\\_work\\dqx-offline-localization\\dqx-offline-localization\\20250626\\staging\\\\${lang}\\Game\\Content\\NonAssets\\\ETP\*\" \"../../../${DESTINATION}/Content/NonAssets/ETP/\"\
                  \"..\\..\\..\\..\\\actions-runner\\_work\\dqx-offline-localization\\dqx-offline-localization\\20250626\\staging\\\\${lang}\\Game\\Content\\NonAssets\\\ETP_ko\*\" \"../../../${DESTINATION}/Content/NonAssets/ETP_ko/\"\
                  \"..\\..\\..\\..\\\actions-runner\\_work\\dqx-offline-localization\\dqx-offline-localization\\20250626\\staging\\\\${lang}\\Game\\Content\\Localization\\Game\\\\${lang}\\Game.locres\" \"../../../${DESTINATION}/Content/Localization/Game/ko/Game.locres\"\
                  \"..\\..\\..\\..\\\actions-runner\\_work\\dqx-offline-localization\\dqx-offline-localization\\20250626\\staging\\\\${lang}\\Game\\Content\\Settings\\Version\\\version_settings.json\" \"../../../${DESTINATION}/Content/Settings/Version/version_settings.json\"\
                  " | sed -e 's/                  /\n/g ; s/^[[:space:]]*//g ; s/[[:space:]]*$//g' > ${{ github.workspace }}/20250626/staging/responseFile--pakchunk0-${PLATFORM}_Latest.pak.txt
                echo "::endgroup::"

                echo -e "::group::Creating \033[0;34m pakchunk0-${PLATFORM}_${lang}_Dialogue_Latest_P.pak \033[0m"
                  ~/UnrealEngine-4.27.2-release/Engine/Binaries/Linux/UnrealPak \
                  "../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/${lang}/pakchunk0-${PLATFORM}_${lang}_Dialogue_Latest_P.pak" \
                  -Create="../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/responseFile--pakchunk0-${PLATFORM}_Latest.pak.txt"
                echo "::endgroup::"

                echo -e "::group::Creating \033[0;34m pakchunk0-${PLATFORM}_${lang}_Dialogue_Latest_P.pak.zip \033[0m"
                  zip -uj \
                  ${{ github.workspace }}/20250626/staging/releases/pakchunk0-${PLATFORM}_${lang}_Dialogue_Latest_P.pak.zip \
                  ${{ github.workspace }}/20250626/staging/${lang}/pakchunk0-${PLATFORM}_${lang}_Dialogue_Latest_P.pak
                echo "::endgroup::"
            done;
            echo -e "\n::notice::\033[0;32m Successfully created: \033[0;34m pakchunk0-${PLATFORM}_${lang}_Dialogue_Latest_P.pak \033[0m"
          done;
########################################################################################################################################################################################################
# 2025-06-26
#  UnrealPak_-Create:
#    needs: [Checkout_Repos, LocRes-Builder, YAML_to_ETP]
#    runs-on: self-hosted
#    steps:
#      - name: UnrealPak -Create
#        run: |
#          for lang in de en es fr it ja ko pt-BR zh-Hans zh-Hant; do \
#            mkdir -p ${{ github.workspace }}/20250626/staging/${lang}/Game/Content/NonAssets/ETP_ko
#            
#            cp ${{ github.workspace }}/20250626/staging/${lang}/Game/Content/NonAssets/ETP/* \
#            ${{ github.workspace }}/20250626/staging/${lang}/Game/Content/NonAssets/ETP_ko
#            ########################################################################################################################################################################################################
#            # echo -e "::group::Creating \033[0;34m pakchunk0-ios_${lang}_Dialogue_Latest_P.pak \033[0m"
#            # ~/UnrealEngine-4.27.2-release/Engine/Binaries/Linux/UnrealPak \
#            # "../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/${lang}/pakchunk0-ios_${lang}_Dialogue_Latest_P.pak" \
#            # -Create="../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/Holiday/response_file--pakchunk0-ios_${lang}_Latest.pak.txt"
#            # echo "::endgroup::"
#            
#            # echo -e "::group::Listing \033[0;32m pakchunk0-ios_${lang}_Dialogue_Latest_P.pak \033[0m"
#            # ~/UnrealEngine-4.27.2-release/Engine/Binaries/Linux/UnrealPak \
#            # "../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/${lang}/pakchunk0-ios_${lang}_Dialogue_Latest_P.pak" \
#            # -Create="../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/Holiday/response_file--pakchunk0-ios_${lang}_Latest.pak.txt" \
#            # -List
#            # echo "::endgroup::"
#            ########################################################################################################################################################################################################
#            echo -e "::group::Creating \033[0;34m pakchunk0-Switch_${lang}_Dialogue_Latest_P.pak \033[0m"
#              ~/UnrealEngine-4.27.2-release/Engine/Binaries/Linux/UnrealPak \
#              "../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/${lang}/pakchunk0-Switch_${lang}_Dialogue_Latest_P.pak" \
#              -Create="../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/response_file--pakchunk0-Switch_${lang}_Latest.pak.txt"
#            echo "::endgroup::"
#
#            echo -e "::group::Listing \033[0;32m pakchunk0-Switch_${lang}_Dialogue_Latest_P.pak \033[0m"
#              ~/UnrealEngine-4.27.2-release/Engine/Binaries/Linux/UnrealPak \
#              "../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/${lang}/pakchunk0-Switch_${lang}_Dialogue_Latest_P.pak" \
#              -Create="../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/response_file--pakchunk0-Switch_${lang}_Latest.pak.txt" \
#              -List
#            echo "::endgroup::"
#
#            echo -e "::group::Creating \033[0;34m pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak \033[0m"
#              ~/UnrealEngine-4.27.2-release/Engine/Binaries/Linux/UnrealPak \
#              "../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/${lang}/pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak" \
#              -Create="../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/response_file--pakchunk0-WindowsNoEditor_${lang}_Latest.pak.txt"
#            echo "::endgroup::"
#
#            echo -e "::group::Listing \033[0;32m pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak \033[0m"
#              ~/UnrealEngine-4.27.2-release/Engine/Binaries/Linux/UnrealPak \
#              "../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/${lang}/pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak" \
#              -Create="../../../../actions-runner/_work/dqx-offline-localization/dqx-offline-localization/20250626/staging/response_file--pakchunk0-WindowsNoEditor_${lang}_Latest.pak.txt" \
#              -List
#            echo "::endgroup::"
#
#            ## echo "Successfully created: [pakchunk0-ios_${lang}_Dialogue_Latest_P.pak](https://github.com/KodywithaK/dqx-offline-localization/releases/download/Latest/pakchunk0-ios_${lang}_Dialogue_Latest_P.pak)" >> $GITHUB_STEP_SUMMARY
#            ## echo -e "\n::notice::\033[0;32m Successfully created: \033[0;34m pakchunk0-ios_${lang}_Dialogue_Latest_P.pak \033[0m\n\033[0;32m Successfully created: \033[0;34m pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak \033[0m"
#
#            ## echo "Successfully created: [pakchunk0-Switch_${lang}_Dialogue_Latest_P.pak](https://github.com/KodywithaK/dqx-offline-localization/releases/download/Latest/pakchunk0-Switch_${lang}_Dialogue_Latest_P.pak)" >> $GITHUB_STEP_SUMMARY
#            #echo -e "\n::notice::\033[0;32m Successfully created: \033[0;34m pakchunk0-Switch_${lang}_Dialogue_Latest_P.pak \033[0m\n\033[0;32m Successfully created: \033[0;34m pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak \033[0m"
#
#            ## echo "Successfully created: [pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak](https://github.com/KodywithaK/dqx-offline-localization/releases/download/Latest/pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak)" >> $GITHUB_STEP_SUMMARY
#            #echo -e "\n::notice::\033[0;32m Successfully created: \033[0;34m pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak \033[0m"
#
#            ## echo "Successfully created: [pakchunk0-{PLATFORM}_${lang}_Dialogue_Latest_P.pak](https://github.com/KodywithaK/dqx-offline-localization/releases/tag/Multi-Languages)" >> $GITHUB_STEP_SUMMARY
#            echo -e "\n::notice::\033[0;32m Successfully created: \033[0;34m pakchunk0-{PLATFORM}_${lang}_Dialogue_Latest_P.pak \033[0m"
#          done
#
#  Create_Latest_Release:
#    needs: [Checkout_Repos, LocRes-Builder, YAML_to_ETP, UnrealPak_-Create]
#    runs-on: self-hosted
#    steps:
#      - name: Zip Files
#        run: |
#          mkdir -p "${{ github.workspace }}/20250626/staging/releases"
#          for lang in de en es fr it ja ko pt-BR zh-Hans zh-Hant; do \
#            zip -uj \
#            ${{ github.workspace }}/20250626/staging/releases/pakchunk0-Switch_${lang}_Dialogue_Latest_P.pak.zip \
#            ${{ github.workspace }}/20250626/staging/${lang}/pakchunk0-Switch_${lang}_Dialogue_Latest_P.pak
#            
#            zip -uj \
#            ${{ github.workspace }}/20250626/staging/releases/pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak.zip \
#            ${{ github.workspace }}/20250626/staging/${lang}/pakchunk0-WindowsNoEditor_${lang}_Dialogue_Latest_P.pak
#          done
####################################################################################################
#      - name: Create Release
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          gh release delete Multi-Languages --yes
#
#          gh release create Multi-Languages \
#          ${{ github.workspace }}/20250626/staging/releases/pakchunk0-Switch_*_Dialogue_Latest_P.pak.zip \
#          ${{ github.workspace }}/20250626/staging/releases/pakchunk0-WindowsNoEditor_*_Dialogue_Latest_P.pak.zip \
#          --notes-file ${{ github.workspace }}/20250626/dqx-offline-localization/docs/CHANGELOG.md \
#          --title "$(echo -e v$(date -u +%F ))"
#
#          echo "Successfully uploaded new files to [Releases/Multi-Languages](https://github.com/KodywithaK/dqx-offline-localization/releases/tag/Multi-Languages)." >> $GITHUB_STEP_SUMMARY
#          echo -e "\n::notice:: \033[0;32m Successfully uploaded new files to Latest release. \033[0m"
#
####################################################################################################
# 2025-02-20
# - `HTTP 422: Validation Failed`
#   - ja/Game.locres causing *.pak to go over file size upload limit or existing Draft Release bug?
# gh release delete Multi-Language --yes
# gh release create Multi-Language \
# ${{ github.workspace }}/test/staging/*/pakchunk0-Switch_*_Dialogue_Latest_P.pak \
# ${{ github.workspace }}/test/staging/*/pakchunk0-WindowsNoEditor_*_Dialogue_Latest_P.pak \
####################################################################################################
